function str(k, c, fb = '') { const v = c[k]; return v !== undefined && v !== '' ? String(v) : fb; }
function n(v, fb = 0) { return Number(v ?? fb); }
function b(v, fb = false) { return v !== undefined ? Boolean(v) : fb; }

function indent(s, spaces) {
  return s.split('\n').map(l => l.trim() ? ' '.repeat(spaces) + l : l).join('\n');
}

export function generateAnsiblePlaybook(nodes, edges = []) {
  if (nodes.length === 0) return '# Drag Ansible tasks onto the canvas to generate a playbook\n';

  const hostNodes = nodes.filter(n => n.data.definition.label === 'Host Group');
  const taskNodes = nodes.filter(n => n.data.definition.label !== 'Host Group');

  const plays = [];

  plays.push(`---
# ============================================================
# Ansible Playbook
# Generated by Terraform Visual Builder
# ============================================================
`);

  const inventoryLines = ['[all]'];
  hostNodes.forEach(hn => {
    const c = hn.data.config;
    const hosts = str('hosts', c, '').split(',').map(h => h.trim()).filter(Boolean);
    const group = str('group_name', c, 'servers');
    inventoryLines.push('');
    inventoryLines.push(`[${group}]`);
    hosts.forEach(host => {
      inventoryLines.push(`${host} ansible_user=${str('ansible_user', c, 'ubuntu')} ansible_port=${n(c.ansible_port, 22)}`);
    });
  });

  plays.push(`# ── Inventory (save as inventory.ini) ──────────────────────────────────────
# ${inventoryLines.join('\n# ')}
`);

  if (hostNodes.length === 0) {
    const tasks = buildTasks(taskNodes);
    const handlers = buildHandlers(taskNodes);
    plays.push(`- name: Main Playbook
  hosts: all
  become: true
  gather_facts: true

  vars:
    app_env: production

  tasks:
${indent(tasks, 4)}
${handlers ? `  handlers:\n${indent(handlers, 4)}` : ''}`);
  } else {
    const hostToTasks = new Map();
    hostNodes.forEach(hn => hostToTasks.set(hn.id, []));

    taskNodes.forEach(taskNode => {
      const connectedHostIds = new Set();

      edges.forEach(edge => {
        if (edge.source === taskNode.id && hostNodes.find(h => h.id === edge.target)) {
          connectedHostIds.add(edge.target);
        }
        if (edge.target === taskNode.id && hostNodes.find(h => h.id === edge.source)) {
          connectedHostIds.add(edge.source);
        }
      });

      if (connectedHostIds.size > 0) {
        connectedHostIds.forEach(hostId => {
          const arr = hostToTasks.get(hostId) ?? [];
          arr.push(taskNode);
          hostToTasks.set(hostId, arr);
        });
      } else {
        hostNodes.forEach(hn => {
          const arr = hostToTasks.get(hn.id) ?? [];
          arr.push(taskNode);
          hostToTasks.set(hn.id, arr);
        });
      }
    });

    hostNodes.forEach(hn => {
      const c = hn.data.config;
      const group = str('group_name', c, 'servers');
      const myTasks = hostToTasks.get(hn.id) ?? taskNodes;
      const tasks = buildTasks(myTasks);
      const handlers = buildHandlers(myTasks);
      plays.push(`- name: Play for ${group}
  hosts: ${group}
  become: ${b(c.become, true)}
  gather_facts: true

  vars:
    app_env: production

  tasks:
${indent(tasks, 4)}
${handlers ? `  handlers:\n${indent(handlers, 4)}` : ''}`);
    });
  }

  return plays.join('\n') + '\n';
}

function buildTasks(taskNodes) {
  if (taskNodes.length === 0) return '    - name: No tasks defined\n      debug:\n        msg: "Add tasks from the sidebar"';

  const lines = [];

  for (const node of taskNodes) {
    const c = node.data.config;
    const label = node.data.definition.label;
    const taskName = str('task_name', c, label);
    const when = str('when', c, '');
    const notify = str('notify', c, '');
    const register = str('register', c, '');
    const become = b(c.become, false);

    let taskBlock = '';

    if (label === 'Install Package') {
      const pkgMgr = str('package_manager', c, 'apt');
      const pkgs = str('package_name', c, 'nginx').split(',').map(p => p.trim()).filter(Boolean);
      if (pkgMgr === 'pip' || pkgMgr === 'npm' || pkgMgr === 'gem') {
        taskBlock = `- name: "${taskName}"
  ${pkgMgr}:
    name:
${pkgs.map(p => `      - ${p}`).join('\n')}
    state: ${str('state', c, 'present')}`;
      } else {
        taskBlock = `- name: "${taskName}"
  ${pkgMgr}:
    name:
${pkgs.map(p => `      - ${p}`).join('\n')}
    state: ${str('state', c, 'present')}
    update_cache: ${b(c.update_cache, true)}`;
      }
    } else if (label === 'Manage Service') {
      taskBlock = `- name: "${taskName}"
  service:
    name: ${str('service_name', c, 'nginx')}
    state: ${str('state', c, 'started')}
    enabled: ${b(c.enabled, true)}`;
    } else if (label === 'Copy File') {
      taskBlock = `- name: "${taskName}"
  copy:
    src: ${str('src', c, 'files/file')}
    dest: ${str('dest', c, '/tmp/file')}${str('owner', c) ? '\n    owner: ' + str('owner', c) : ''}${str('group', c) ? '\n    group: ' + str('group', c) : ''}${str('mode', c) ? '\n    mode: "' + str('mode', c) + '"' : ''}
    backup: ${b(c.backup, false)}`;
    } else if (label === 'Template File') {
      taskBlock = `- name: "${taskName}"
  template:
    src: ${str('src', c, 'templates/file.j2')}
    dest: ${str('dest', c, '/tmp/file')}${str('owner', c) ? '\n    owner: ' + str('owner', c) : ''}${str('group', c) ? '\n    group: ' + str('group', c) : ''}${str('mode', c) ? '\n    mode: "' + str('mode', c) + '"' : ''}`;
    } else if (label === 'Run Command') {
      taskBlock = `- name: "${taskName}"
  shell: ${str('command', c, 'echo hello')}${str('chdir', c) ? '\n  args:\n    chdir: ' + str('chdir', c) : ''}${str('creates', c) ? '\n    creates: ' + str('creates', c) : ''}${str('removes', c) ? '\n    removes: ' + str('removes', c) : ''}`;
    } else if (label === 'Manage User') {
      taskBlock = `- name: "${taskName}"
  user:
    name: ${str('username', c, 'deploy')}
    state: ${str('state', c, 'present')}${str('groups', c) ? '\n    groups: ' + str('groups', c) : ''}
    shell: ${str('shell', c, '/bin/bash')}
    create_home: ${b(c.create_home, true)}${str('password', c) ? '\n    password: "' + str('password', c) + '"' : ''}`;
    } else if (label === 'Git Clone / Pull') {
      taskBlock = `- name: "${taskName}"
  git:
    repo: ${str('repo', c, 'https://github.com/org/repo.git')}
    dest: ${str('dest', c, '/opt/app')}
    version: ${str('version', c, 'main')}
    force: ${b(c.force, false)}
    depth: ${n(c.depth, 1)}${str('key_file', c) ? '\n    key_file: ' + str('key_file', c) : ''}`;
    } else if (label === 'Docker Container') {
      const ports = str('ports', c, '').split(',').map(p => p.trim()).filter(Boolean);
      const vols = str('volumes', c, '').split(',').map(v => v.trim()).filter(Boolean);
      const envs = str('env_vars', c, '').split(',').map(e => e.trim()).filter(Boolean);
      taskBlock = `- name: "${taskName}"
  community.docker.docker_container:
    name: ${str('container_name', c, 'mycontainer')}
    image: ${str('image', c, 'nginx:latest')}
    state: ${str('state', c, 'started')}
    restart_policy: ${str('restart_policy', c, 'unless-stopped')}
    pull: ${b(c.pull, false)}${ports.length ? '\n    ports:\n' + ports.map(p => `      - "${p}"`).join('\n') : ''}${vols.length ? '\n    volumes:\n' + vols.map(v => `      - "${v}"`).join('\n') : ''}${envs.length ? '\n    env:\n' + envs.map(e => { const [k,v] = e.split('='); return `      ${k}: "${v||''}"`; }).join('\n') : ''}`;
    } else if (label === 'UFW Firewall Rule') {
      taskBlock = `- name: "${taskName}"
  community.general.ufw:
    rule: ${str('rule', c, 'allow')}${str('port', c) ? '\n    port: "' + str('port', c) + '"' : ''}
    proto: ${str('proto', c, 'tcp')}${str('from_ip', c) ? '\n    from_ip: ' + str('from_ip', c) : ''}
    direction: ${str('direction', c, 'in')}
    state: ${str('state', c, 'enabled')}`;
    } else if (label === 'Set Variables') {
      const vars = [];
      for (let i = 1; i <= 3; i++) {
        const k = str(`var${i}_key`, c, '');
        const v = str(`var${i}_value`, c, '');
        if (k) vars.push(`    ${k}: "${v}"`);
      }
      taskBlock = `- name: "${taskName}"
  set_fact:
${vars.join('\n') || '    my_var: "my_value"'}`;
    } else {
      taskBlock = `- name: "${taskName}"
  debug:
    msg: "Task: ${label}"`;
    }

    if (become) taskBlock += '\n  become: true';
    if (when) taskBlock += `\n  when: ${when}`;
    if (notify) taskBlock += `\n  notify: "${notify}"`;
    if (register) taskBlock += `\n  register: ${register}`;

    lines.push(taskBlock);
  }

  return lines.join('\n\n');
}

function buildHandlers(taskNodes) {
  const handlers = new Set<string>();
  taskNodes.forEach(n => {
    const notify = str('notify', n.data.config, '');
    if (notify) handlers.add(notify);
  });

  if (handlers.size === 0) return '';

  const lines = [];
  handlers.forEach(h => {
    const serviceName = h.replace(/^restart /, '').replace(/^reload /, '');
    const action = h.startsWith('reload') ? 'reloaded' : 'restarted';
    lines.push(`- name: "${h}"
  service:
    name: ${serviceName}
    state: ${action}`);
  });

  return lines.join('\n\n');
}

export function generateInventoryFile(nodes) {
  const hostNodes = nodes.filter(n => n.data.definition.label === 'Host Group');
  if (hostNodes.length === 0) return '[all]\nlocalhost ansible_connection=local\n';

  const lines = [];
  const allHosts = [];

  hostNodes.forEach(hn => {
    const c = hn.data.config;
    const group = str('group_name', c, 'servers');
    const hosts = str('hosts', c, '').split(',').map(h => h.trim()).filter(Boolean);
    const user = str('ansible_user', c, 'ubuntu');
    const port = n(c.ansible_port, 22);
    const keyFile = str('ansible_ssh_private_key_file', c, '');
    const python = str('ansible_python_interpreter', c, '/usr/bin/python3');

    lines.push(`[${group}]`);
    hosts.forEach(host => {
      let hostLine = `${host} ansible_user=${user} ansible_port=${port}`;
      if (keyFile) hostLine += ` ansible_ssh_private_key_file=${keyFile}`;
      hostLine += ` ansible_python_interpreter=${python}`;
      lines.push(hostLine);
      allHosts.push(host);
    });
    lines.push('');
    lines.push(`[${group}:vars]`);
    lines.push(`ansible_become=${b(c.become, true)}`);
    lines.push('');
  });

  if (hostNodes.length > 1) {
    lines.push('[all:children]');
    hostNodes.forEach(hn => lines.push(str('group_name', hn.data.config, 'servers')));
  }

  return lines.join('\n') + '\n';
}
