export const ENV_DEFAULTS = {
  dev: {
    label: 'Development',
    instanceSize: 't3.micro',
    minCount: 1,
    maxCount: 2,
    deletionProtection: false,
    highAvailability: false,
    logRetentionDays: 7,
    backupRetentionDays: 1,
  },
  staging: {
    label: 'Staging',
    instanceSize: 't3.small',
    minCount: 1,
    maxCount: 4,
    deletionProtection: false,
    highAvailability: false,
    logRetentionDays: 14,
    backupRetentionDays: 7,
  },
  prod: {
    label: 'Production',
    instanceSize: 't3.medium',
    minCount: 2,
    maxCount: 10,
    deletionProtection: true,
    highAvailability: true,
    logRetentionDays: 90,
    backupRetentionDays: 30,
  },
};

function header(env, provider) {
  const cfg = ENV_DEFAULTS[env];
  return `# ============================================================
# Environment : ${cfg.label.toUpperCase()} (${env})
# Provider    : ${provider}
# Generated by Terraform Visual Builder
# ============================================================
`;
}

function awsVariablesTf(nodes, region) {
  const lines = [];

  lines.push(`# ============================================================
# variables.tf — AWS
# All environment-specific values are supplied via .tfvars files
# ============================================================

variable "environment" {
  description = "Deployment environment"
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "${region}"
}

variable "aws_profile" {
  description = "AWS CLI profile"
  type        = string
  default     = "default"
}

variable "project_name" {
  description = "Project name used for resource naming and tagging"
  type        = string
}

variable "instance_type" {
  description = "EC2 / compute instance type"
  type        = string
}

variable "min_count" {
  description = "Minimum number of instances / nodes"
  type        = number
}

variable "max_count" {
  description = "Maximum number of instances / nodes"
  type        = number
}

variable "deletion_protection" {
  description = "Enable deletion protection on stateful resources"
  type        = bool
}

variable "high_availability" {
  description = "Enable multi-AZ / high-availability mode"
  type        = bool
}

variable "log_retention_days" {
  description = "CloudWatch log retention in days"
  type        = number
}

variable "backup_retention_days" {
  description = "Database backup retention in days"
  type        = number
}
`);

  const seen = new Set();
  for (const node of nodes) {
    const { resourceType, resourceName, config } = node.data;
    const safe = resourceName.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    if (resourceType === 'aws_instance' && config.ami && !seen.has('ami_id')) {
      seen.add('ami_id');
      lines.push(`variable "ami_id" {
  description = "AMI ID for EC2 instances"
  type        = string
}
`);
    }

    if ((resourceType === 'aws_rds_instance' || resourceType === 'aws_rds_cluster') && !seen.has(`${safe}_db_password`)) {
      seen.add(`${safe}_db_password`);
      lines.push(`variable "${safe}_db_password" {
  description = "Master password for ${resourceName} database"
  type        = string
  sensitive   = true
}
`);
    }

    if (resourceType === 'aws_s3_bucket' && config.bucket && !seen.has(`${safe}_bucket_name`)) {
      seen.add(`${safe}_bucket_name`);
      lines.push(`variable "${safe}_bucket_name" {
  description = "S3 bucket name for ${resourceName}"
  type        = string
}
`);
    }

    if (resourceType === 'aws_vpc' && config.cidr_block && !seen.has(`${safe}_cidr`)) {
      seen.add(`${safe}_cidr`);
      lines.push(`variable "${safe}_cidr" {
  description = "CIDR block for ${resourceName} VPC"
  type        = string
}
`);
    }
  }

  return lines.join('\n');
}

function awsTfvars(env, nodes, region) {
  const cfg = ENV_DEFAULTS[env];
  const lines = [header(env, 'AWS')];

  lines.push(`environment           = "${env}"`);
  lines.push(`aws_region            = "${region}"`);
  lines.push(`aws_profile           = "default"`);
  lines.push(`project_name          = "my-project-${env}"`);
  lines.push(`instance_type         = "${cfg.instanceSize}"`);
  lines.push(`min_count             = ${cfg.minCount}`);
  lines.push(`max_count             = ${cfg.maxCount}`);
  lines.push(`deletion_protection   = ${cfg.deletionProtection}`);
  lines.push(`high_availability     = ${cfg.highAvailability}`);
  lines.push(`log_retention_days    = ${cfg.logRetentionDays}`);
  lines.push(`backup_retention_days = ${cfg.backupRetentionDays}`);
  lines.push('');

  const seen = new Set();
  for (const node of nodes) {
    const { resourceType, resourceName, config } = node.data;
    const safe = resourceName.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    if (resourceType === 'aws_instance' && config.ami && !seen.has('ami_id')) {
      seen.add('ami_id');
      lines.push(`ami_id = "${config.ami}"`);
    }
    if ((resourceType === 'aws_rds_instance' || resourceType === 'aws_rds_cluster') && !seen.has(`${safe}_db_password`)) {
      seen.add(`${safe}_db_password`);
      const envSuffix = env === 'prod' ? 'CHANGE_ME_PROD' : env === 'staging' ? 'CHANGE_ME_STAGING' : 'CHANGE_ME_DEV';
      lines.push(`${safe}_db_password = "${envSuffix}"`);
    }
    if (resourceType === 'aws_s3_bucket' && config.bucket && !seen.has(`${safe}_bucket_name`)) {
      seen.add(`${safe}_bucket_name`);
      lines.push(`${safe}_bucket_name = "${config.bucket}-${env}"`);
    }
    if (resourceType === 'aws_vpc' && config.cidr_block && !seen.has(`${safe}_cidr`)) {
      seen.add(`${safe}_cidr`);
      const shift = env === 'dev' ? 0 : env === 'staging' ? 1 : 2;
      const cidr = String(config.cidr_block).replace(/^(\d+\.)(\d+)(\..*)$/, (_, a, b, c) => `${a}${Number(b) + shift}${c}`);
      lines.push(`${safe}_cidr = "${cidr}"`);
    }
  }

  return lines.join('\n') + '\n';
}

function awsProvidersTf(region) {
  return `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment to use remote state per environment:
  # backend "s3" {
  #   bucket = "my-terraform-state-\${var.environment}"
  #   key    = "\${var.environment}/terraform.tfstate"
  #   region = "${region}"
  # }
}

provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile

  default_tags {
    tags = {
      ManagedBy   = "Terraform"
      Environment = var.environment
      Project     = var.project_name
    }
  }
}
`;
}

const AZURE_VM_SIZE = {
  dev:     'Standard_B1s',
  staging: 'Standard_B2s',
  prod:    'Standard_D4s_v3',
};

function azureVariablesTf() {
  return `# ============================================================
# variables.tf — Azure
# All environment-specific values are supplied via .tfvars files
# ============================================================

variable "environment" {
  description = "Deployment environment"
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "subscription_id" {
  description = "Azure Subscription ID"
  type        = string
  sensitive   = true
}

variable "location" {
  description = "Azure region / location"
  type        = string
  default     = "East US"
}

variable "project_name" {
  description = "Project name used for resource naming and tagging"
  type        = string
}

variable "vm_size" {
  description = "Azure VM size"
  type        = string
}

variable "node_count" {
  description = "Default node / instance count"
  type        = number
}

variable "deletion_protection" {
  description = "Enable deletion protection on stateful resources"
  type        = bool
}

variable "high_availability" {
  description = "Enable zone-redundant / high-availability mode"
  type        = bool
}

variable "log_retention_days" {
  description = "Log Analytics retention in days"
  type        = number
}

variable "backup_retention_days" {
  description = "Database backup retention in days"
  type        = number
}

variable "admin_password" {
  description = "Default admin password for VMs and databases"
  type        = string
  sensitive   = true
}
`;
}

function azureTfvars(env) {
  const cfg = ENV_DEFAULTS[env];
  const lines = [header(env, 'Azure')];

  lines.push(`environment           = "${env}"`);
  lines.push(`subscription_id       = "YOUR_SUBSCRIPTION_ID"`);
  lines.push(`location              = "East US"`);
  lines.push(`project_name          = "my-project-${env}"`);
  lines.push(`vm_size               = "${AZURE_VM_SIZE[env]}"`);
  lines.push(`node_count            = ${cfg.minCount}`);
  lines.push(`deletion_protection   = ${cfg.deletionProtection}`);
  lines.push(`high_availability     = ${cfg.highAvailability}`);
  lines.push(`log_retention_days    = ${cfg.logRetentionDays}`);
  lines.push(`backup_retention_days = ${cfg.backupRetentionDays}`);
  lines.push(`admin_password        = "CHANGE_ME_${env.toUpperCase()}"`);

  return lines.join('\n') + '\n';
}

function azureProvidersTf() {
  return `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  # Uncomment to use remote state per environment:
  # backend "azurerm" {
  #   resource_group_name  = "terraform-state-rg"
  #   storage_account_name = "tfstate\${var.environment}"
  #   container_name       = "tfstate"
  #   key                  = "\${var.environment}.terraform.tfstate"
  # }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}
`;
}

const GCP_MACHINE_TYPE = {
  dev:     'e2-micro',
  staging: 'e2-small',
  prod:    'e2-standard-4',
};

function gcpVariablesTf(region) {
  return `# ============================================================
# variables.tf — GCP
# All environment-specific values are supplied via .tfvars files
# ============================================================

variable "environment" {
  description = "Deployment environment"
  type        = string

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "project_id" {
  description = "GCP Project ID"
  type        = string
}

variable "region" {
  description = "GCP region"
  type        = string
  default     = "${region}"
}

variable "project_name" {
  description = "Project name used for resource naming and labels"
  type        = string
}

variable "machine_type" {
  description = "GCP Compute Engine machine type"
  type        = string
}

variable "min_count" {
  description = "Minimum number of instances / nodes"
  type        = number
}

variable "max_count" {
  description = "Maximum number of instances / nodes"
  type        = number
}

variable "deletion_protection" {
  description = "Enable deletion protection on stateful resources"
  type        = bool
}

variable "high_availability" {
  description = "Enable regional / high-availability mode"
  type        = bool
}

variable "log_retention_days" {
  description = "Log retention in days"
  type        = number
}

variable "backup_retention_days" {
  description = "Database backup retention in days"
  type        = number
}
`;
}

function gcpTfvars(env, region) {
  const cfg = ENV_DEFAULTS[env];
  const lines = [header(env, 'GCP')];

  lines.push(`environment           = "${env}"`);
  lines.push(`project_id            = "YOUR_PROJECT_ID_${env.toUpperCase()}"`);
  lines.push(`region                = "${region}"`);
  lines.push(`project_name          = "my-project-${env}"`);
  lines.push(`machine_type          = "${GCP_MACHINE_TYPE[env]}"`);
  lines.push(`min_count             = ${cfg.minCount}`);
  lines.push(`max_count             = ${cfg.maxCount}`);
  lines.push(`deletion_protection   = ${cfg.deletionProtection}`);
  lines.push(`high_availability     = ${cfg.highAvailability}`);
  lines.push(`log_retention_days    = ${cfg.logRetentionDays}`);
  lines.push(`backup_retention_days = ${cfg.backupRetentionDays}`);

  return lines.join('\n') + '\n';
}

function gcpProvidersTf(_region) {
  return `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }

  # Uncomment to use remote state per environment:
  # backend "gcs" {
  #   bucket = "my-terraform-state-\${var.environment}"
  #   prefix = "\${var.environment}/terraform.tfstate"
  # }
}

provider "google" {
  project = var.project_id
  region  = var.region
}
`;
}

function envReadme(provider, region) {
  const providerName = provider === 'aws' ? 'AWS' : provider === 'azure' ? 'Azure' : 'GCP';
  const varFileFlag = '-var-file="envs/dev.tfvars"';

  return `# Terraform Infrastructure — ${providerName}

> Generated by [Terraform Visual Builder](https://github.com/your-repo)

## Environment-Based Approach

This project uses **per-environment \`.tfvars\` files** to manage configuration
across \`dev\`, \`staging\`, and \`prod\` without duplicating resource definitions.

\`\`\`
.
├── main.tf               # Resource definitions (shared across all envs)
├── providers.tf          # Provider + backend configuration
├── variables.tf          # Variable declarations (no defaults — set in tfvars)
├── outputs.tf            # Output values
└── envs/
    ├── dev.tfvars        # Development environment values
    ├── staging.tfvars    # Staging environment values
    └── prod.tfvars       # Production environment values
\`\`\`

## Quick Start

\`\`\`bash
# 1. Initialise
terraform init

# 2. Plan for a specific environment
terraform plan ${varFileFlag}

# 3. Apply
terraform apply ${varFileFlag}

# 4. Destroy
terraform destroy ${varFileFlag}
\`\`\`

## Environment Differences

| Variable              | dev          | staging      | prod              |
|-----------------------|--------------|--------------|-------------------|
| instance_type / size  | small        | medium       | large             |
| min_count             | 1            | 1            | 2                 |
| max_count             | 2            | 4            | 10                |
| deletion_protection   | false        | false        | true              |
| high_availability     | false        | false        | true              |
| log_retention_days    | 7            | 14           | 90                |
| backup_retention_days | 1            | 7            | 30                |

## Security Notes

- ⚠️  Never commit \`prod.tfvars\` with real credentials — use a secrets manager.
- ⚠️  Sensitive variables (passwords, subscription IDs) are marked \`sensitive = true\`.
- ✅  All resources are tagged/labelled with \`Environment\` and \`Project\`.
- ✅  Remote state backend config is included (commented out) in \`providers.tf\`.

## Region

Default region: **${region}**
`;
}

export function buildEnvTerraformProject(
  provider,
  nodes,
  region,
  mainTfContent,
  outputsTfContent,
) {
  let variablesTf;
  let providersTf;
  let devTfvars;
  let stagingTfvars;
  let prodTfvars;

  switch (provider) {
    case 'aws':
      variablesTf  = awsVariablesTf(nodes, region);
      providersTf  = awsProvidersTf(region);
      devTfvars    = awsTfvars('dev',     nodes, region);
      stagingTfvars = awsTfvars('staging', nodes, region);
      prodTfvars   = awsTfvars('prod',    nodes, region);
      break;

    case 'azure':
      variablesTf  = azureVariablesTf();
      providersTf  = azureProvidersTf();
      devTfvars    = azureTfvars('dev');
      stagingTfvars = azureTfvars('staging');
      prodTfvars   = azureTfvars('prod');
      break;

    case 'gcp':
      variablesTf  = gcpVariablesTf(region);
      providersTf  = gcpProvidersTf(region);
      devTfvars    = gcpTfvars('dev',     region);
      stagingTfvars = gcpTfvars('staging', region);
      prodTfvars   = gcpTfvars('prod',    region);
      break;

    default:
      variablesTf  = '# No variable definitions for this provider\n';
      providersTf  = '# No provider configuration for this provider\n';
      devTfvars    = '# dev\n';
      stagingTfvars = '# staging\n';
      prodTfvars   = '# prod\n';
  }

  const cleanMain = stripProviderBlock(mainTfContent);

  return {
    'main.tf':              cleanMain,
    'providers.tf':         providersTf,
    'variables.tf':         variablesTf,
    'outputs.tf':           outputsTfContent || '# No outputs defined\n',
    'envs/dev.tfvars':      devTfvars,
    'envs/staging.tfvars':  stagingTfvars,
    'envs/prod.tfvars':     prodTfvars,
    'README.md':            envReadme(provider, region),
  };
}

function stripProviderBlock(tf) {
  const lines = tf.split('\n');
  const result = [];
  let depth = 0;
  let skipping = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (depth === 0) {
      if (
        trimmed.startsWith('terraform {') ||
        trimmed.startsWith('provider ') ||
        trimmed.startsWith('variable "')
      ) {
        skipping = true;
      }
    }

    if (skipping) {
      for (const ch of line) {
        if (ch === '{') depth++;
        if (ch === '}') depth--;
      }
      if (depth === 0) {
        skipping = false;
        if (i + 1 < lines.length && lines[i + 1].trim() === '') i++;
      }
      continue;
    }

    result.push(line);
  }

  while (result.length > 0 && result[0].trim() === '') result.shift();

  return result.join('\n');
}

export async function downloadEnvProjectAsZip(
  project: Record<string, string>,
  projectName = 'terraform-env-project',
) {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  const folder = zip.folder(projectName);

  for (const [filename, content] of Object.entries(project)) {
    folder.file(filename, content);
  }

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
